#+ endpoint: http://virtuoso-midi.amp.ops.labs.vu.nl/sparql
#+ summary: Search MIDI patterns by original file name

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mid: <http://example.org/midi/>

SELECT ?filename ?pattern
WHERE
{
?pattern prov:wasDerivedFrom ?filename .
FILTER (regex(?filename, ?_query, "i"))
}
