PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mid: <http://example.org/midi/>

SELECT ?filename ?pattern ?track ?event
WHERE
{
?pattern prov:wasDerivedFrom ?filename .
?pattern mid:hasTrack ?track.
?track mid:hasEvent ?event
FILTER (regex(?filename, ?_query, "i"))
} GROUP BY ?pattern ?track ?event
