#+ summary: Get patterns by tempo values
#+ endpoint: http://virtuoso-midi.amp.ops.labs.vu.nl/sparql

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mid: <http://purl.org/midi-ld/midi#>

SELECT DISTINCT ?MIDIpiece ?filename
WHERE {
?MIDIpiece prov:wasDerivedFrom ?filename .
?MIDIpiece mid:hasTrack ?track .
?MIDIpiece mid:resolution ?__resolution_integer .
?track mid:hasEvent ?timesignatureevent .
?timesignatureevent a mid:TimeSignatureEvent .
?timesignatureevent mid:denominator ?__denominator_integer .
?timesignatureevent mid:metronome ?__metronome_integer .
?timesignatureevent mid:numerator ?__numerator_integer .
?timesignatureevent mid:thirtyseconds ?__thirtyseconds_integer .
FILTER (regex(?filename, ?_query, "i")) . 
}
