#+ summary: Get patterns by tempo values
#+ endpoint: http://virtuoso-midi.amp.ops.labs.vu.nl/sparql

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mid: <http://purl.org/midi-ld/midi#>

SELECT DISTINCT ?pattern ?filename
WHERE {
?pattern prov:wasDerivedFrom ?filename .
?pattern mid:hasTrack ?track .
?pattern mid:resolution ?__resolution .
?track mid:hasEvent ?timesignatureevent .
?timesignatureevent a mid:TimeSignatureEvent .
?timesignatureevent mid:denominator ?__denominator .
?timesignatureevent mid:metronome ?__metronome .
?timesignatureevent mid:numerator ?__numerator .
?timesignatureevent mid:thirtyseconds ?__thirtyseconds .
FILTER (regex(?filename, ?__query, "i")) . 
}
