#+ summary: Get patterns by tempo values
#+ endpoint: http://virtuoso-midi.amp.ops.labs.vu.nl/sparql

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mid: <http://purl.org/midi-ld/midi#>

SELECT DISTINCT ?pattern ?filename
WHERE {
?pattern prov:wasDerivedFrom ?filename .
?pattern mid:hasTrack ?track .
?pattern mid:resolution ?_resolution .
?track mid:hasEvent ?timesignatureevent .
?timesignatureevent a mid:TimeSignatureEvent .
?timesignatureevent mid:denominator ?_denominator .
?timesignatureevent mid:metronome ?_metronome .
?timesignatureevent mid:numerator ?_numerator .
?timesignatureevent mid:thirtyseconds ?_thirtyseconds .
FILTER (regex(?filename, ?_query, "i")) . 
}
