#+ endpoint: http://virtuoso-midi.amp.ops.labs.vu.nl/sparql
#+ summary: Search MIDI patterns by their format and resolution values

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX midi: <http://purl.org/midi-ld/midi#>

SELECT * WHERE {
  ?pattern a midi:Pattern .
  ?pattern midi:format ?_format .
  ?pattern midi:resolution ?_resolution .
} GROUP BY ?pattern
